---
- name: download | Owncloud
  get_url:
    url: "https://download.owncloud.com/desktop/stable/owncloudclient-1.8.4.tar.xz"
    dest: "/tmp/owncloud.tar.xz"
    mode: 0440
    validate_certs: no
  notify: extract | Owncloud
