---
- name: download | Owncloud
  get_url:
    url: "https://download.owncloud.org/community/owncloud-{{ owncloud_version }}.tar.bz2"
    dest: "/tmp/owncloud.tar.bz2"
    mode: 0440
    validate_certs: no
  notify: extract | Owncloud
