---
- name: download | Owncloud
  get_url:
    url: "https://download.owncloud.org/community/owncloud-8.2.1.tar.bz2"
    dest: "/tmp/owncloud.tar.bz2"
    mode: 0440
    validate_certs: no

- name: extract | Owncloud
  unarchive:
    src: "/tmp/owncloud.tar.bz2"
    dest: /data/www/docroot/
    copy: no
    owner: www-data
    group: www-data

- name: generate configuration | Owncloud
  command: curl localhost/owncloud/index.php

- name: get id | Owncloud
  shell: "sudo cat /data/www/docroot/owncloud/config/config.php | grep instanceid | awk -F \\' '{ print $4 }'"
  register: owncloud_instanceid

- name: get installed | Owncloud
  shell: "if [ `sudo cat /data/www/docroot/owncloud/config/config.php | grep installed | wc -l` -eq 1 ]; then sudo cat /data/www/docroot/owncloud/config/config.php | grep installed | awk -F \\=\\> '{ print $2 }' | awk -F , '{ print $1 }'; else echo false; fi"
  register: owncloud_installed

- include: overwrite_configuration.yml

- name: setup admin user | Owncloud
  shell: cd /data/www/docroot/owncloud/ && sudo -u www-data php occ  maintenance:install --database "mysql" --database-name "owncloud"  --database-user "root" --database-pass "password" --admin-user "admin" --admin-pass "password"
  ignore_errors: yes

- include: overwrite_configuration.yml

- name: add regular users | Owncloud
  shell: "cd /data/www/docroot/owncloud && sudo -u www-data OC_PASS='{{ item.password }}' php occ user:add --password-from-env {{ item.user }}"
  with_items: owncloud_users
  when: owncloud_users is defined
  ignore_errors: yes
