---
- name: download | Owncloud
  get_url:
    url: "https://download.owncloud.org/community/owncloud-8.2.1.tar.bz2"
    dest: "/tmp/owncloud.tar.bz2"
    mode: 0440
    validate_certs: no

- name: extract | Owncloud
  unarchive:
    src: "/tmp/owncloud.tar.bz2"
    dest: /data/www/docroot/
    copy: no
    owner: www-data
    group: www-data

- name: generate configuration | Owncloud
  command: curl localhost/owncloud/index.php

- include: overwrite_configuration.yml

- name: setup admin user | Owncloud
  shell: cd /data/www/docroot/owncloud/ && sudo -u www-data php occ  maintenance:install --database "mysql" --database-name "owncloud"  --database-user "root" --database-pass "password" --admin-user "admin" --admin-pass "password"
  ignore_errors: yes

- include: overwrite_configuration.yml
