---
- name: download | Owncloud
  get_url:
    url: "https://download.owncloud.org/community/owncloud-8.2.1.tar.bz2"
    dest: "/tmp/owncloud.tar.bz2"
    mode: 0440
    validate_certs: no

- name: extract | Owncloud
  unarchive:
    src: "/tmp/owncloud.tar.bz2"
    dest: /data/www/docroot/
    copy: no
    owner: www-data
    group: www-data

- name: generate configuration | Owncloud
  command: curl localhost/owncloud/index.php

- name: get id | Owncloud
  shell: "sudo cat /data/www/docroot/owncloud/config/config.php | grep instanceid | awk -F \\' '{ print $4 }'"
  register: owncloud_instanceid

- include: overwrite_configuration.yml

- name: setup admin user | Owncloud
  shell: "cd /data/www/docroot/owncloud/ && sudo -u www-data php occ  maintenance:install --database '{{ owncloud_database_type }}' --database-name '{{ project }}'  --database-user '{{ project }}' --database-pass '{{ owncloud_database_password }}' --admin-user '{{ owncloud_admin_user }}' --admin-pass {{ owncloud_admin_password }}"
  ignore_errors: yes

- include: overwrite_configuration.yml

- name: add regular users | Owncloud
  shell: "cd /data/www/docroot/owncloud && sudo -u www-data OC_PASS='{{ item.password }}' php occ user:add --password-from-env {{ item.user }}"
  with_items: owncloud_users
  when: owncloud_users is defined
  ignore_errors: yes
