---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
    update_cache: yes
  with_items:
    - owncloud
  tags:
    - owncloud
    - software-installation
    - using-apt
