---
- name: download
  get_url:
    url: https://download.owncloud.org/community/owncloud-8.2.1.zip
    dest: /tmp/owncloud-8.2.1.zip
    mode: 0440

- name: extract
  unarchive:
    src: /tmp/owncloud-8.2.1.zip
    dest: /data/www/docroot/
    copy: no
