---
- name: overwrite configuration | Owncloud
  template:
    src: owncloud/config/config.php
    dest: /data/www/docroot/owncloud/config/config.php
    owner: www-data
    group: www-data
    mode: 0640