---
- name: extract | Owncloud
  unarchive:
    src: "/tmp/owncloud.tar.bz2"
    dest: /data/www/docroot/
    copy: no
    owner: www-data
    group: www-data
  notify: copy configuration | Owncloud

- name: copy configuration | Owncloud
  template:
    src: owncloud/config/config.php
    dest: /data/www/docroot/owncloud/config/config.php
    owner: www-data
    group: www-data
    mode: 0640
